# Generated by Django 4.2.20 on 2025-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialorder',
            name='billing_address',
            field=models.CharField(default='Unknown address', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialorder',
            name='billing_city',
            field=models.CharField(default='Unknown city', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partialorder',
            name='billing_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='partialorder',
            name='billing_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partialorder',
            name='billing_phone',
            field=models.CharField(max_length=20),
        ),
    ]
