# Generated by Django 4.2.20 on 2025-06-24 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('payment', '0002_partialorder_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon'),
        ),
    ]
