# Generated by Django 4.2.20 on 2025-06-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('payment', '0003_partialorder_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partialorder',
            name='coupon',
        ),
        migrations.AddField(
            model_name='partialorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='coupons.coupon'),
        ),
    ]
