# Generated by Django 4.2.20 on 2025-09-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_partialorder_coupon_partialorder_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialorder',
            name='reward_points_used',
            field=models.IntegerField(default=0),
        ),
    ]
