# Generated by Django 4.2.20 on 2025-06-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vendorreview',
            unique_together=set(),
        ),
    ]
