# Generated by Django 4.2.20 on 2025-09-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('position', models.CharField(choices=[('above_navbar', 'Above Navbar'), ('homepage_middle', 'Homepage Middle'), ('homepage_bottom', 'Homepage Bottom'), ('productpage_sidebar', 'Productpage Sidebar'), ('marketplace', 'Marketplace')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=False)),
                ('paymentDone', models.BooleanField(default=False)),
                ('isApproved', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdAt', 'startDate'],
            },
        ),
    ]
