# Generated by Django 4.2.20 on 2025-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at', 'start_date']},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('above_navbar', 'Above Navbar'), ('middle', 'Middle'), ('bottom', 'Bottom')], max_length=50),
        ),
    ]
