# Generated by Django 4.2.20 on 2025-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-createdAt', 'startDate']},
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='payment_done',
            new_name='paymentDone',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
