# Generated by Django 4.2.20 on 2025-06-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('above_navbar', 'Above Navbar'), ('homepage_middle', 'Homepage Middle'), ('homepage_bottom', 'Homepage Bottom'), ('productpage_sidebar', 'Productpage Sidebar'), ('marketplace', 'Marketplace')], max_length=50),
        ),
    ]
