# Generated by Django 4.2.20 on 2025-06-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisement_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='priority',
        ),
    ]
