# Generated by Django 4.2.20 on 2025-09-17 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(default='Unknown Vendor', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('businessName', models.CharField(default='Unknown Vendor', max_length=255, unique=True)),
                ('businessType', models.CharField(max_length=255)),
                ('businessDescription', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, default='unknown url', max_length=255, null=True)),
                ('registrationNumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('registrationDocument', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(default='Unknown City', max_length=255)),
                ('country', models.CharField(default='Unknown Country', max_length=255)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('appliedAt', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorOrderItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched')], default='Pending', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to='vendors.vendor')),
            ],
        ),
    ]
