# Generated by Django 4.2.20 on 2025-05-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(default='Unknown Vendor', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('businessName', models.CharField(default='Unknown Vendor', max_length=255, unique=True)),
                ('businessType', models.CharField(max_length=255)),
                ('businessDescription', models.TextField(blank=True, null=True)),
                ('registrationNumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(default='Unknown City', max_length=255)),
                ('country', models.CharField(default='Unknown Country', max_length=255)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('appliedAt', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
