# Generated by Django 4.2.20 on 2025-08-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_image_vendororderitemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='registrationDocument',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
