# Generated by Django 4.2.20 on 2025-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_registrationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderitemstatus',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
