# Generated by Django 4.2.20 on 2025-09-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('has_sizes', models.BooleanField(default=False)),
                ('originalPrice', models.CharField(max_length=255)),
                ('discountedPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('discountPercentage', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(default='Unknown url', max_length=255)),
                ('topImage', models.CharField(default='Unknown url', max_length=255)),
                ('bottomImage', models.CharField(default='Unknown url', max_length=255)),
                ('leftImage', models.CharField(default='Unknown url', max_length=255)),
                ('rightImage', models.CharField(default='Unknown url', max_length=255)),
                ('totalStock', models.CharField(default='0', max_length=10)),
                ('isAvailable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('FX', 'Fixed Size')], max_length=2)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
        ),
    ]
