# Generated by Django 4.2.20 on 2025-05-22 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('originalPrice', models.CharField(max_length=255)),
                ('discountedPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(default='Unknown url', max_length=255)),
                ('topImage', models.CharField(default='Unknown url', max_length=255)),
                ('bottomImage', models.CharField(default='Unknown url', max_length=255)),
                ('leftImage', models.CharField(default='Unknown url', max_length=255)),
                ('rightImage', models.CharField(default='Unknown url', max_length=255)),
                ('vendorName', models.CharField(default='Unknown Vendor', max_length=255)),
                ('initialStock', models.CharField(default='0', max_length=10)),
                ('totalStock', models.CharField(default='0', max_length=10)),
                ('isAvailable', models.BooleanField(default=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPlaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=255)),
                ('image', models.CharField(default='Unknown url', max_length=255)),
                ('topImage', models.CharField(default='Unknown url', max_length=255)),
                ('bottomImage', models.CharField(default='Unknown url', max_length=255)),
                ('leftImage', models.CharField(default='Unknown url', max_length=255)),
                ('rightImage', models.CharField(default='Unknown url', max_length=255)),
                ('stock', models.CharField(default='0', max_length=10)),
                ('isAvailable', models.BooleanField(default=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_products_category', to='products.category')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_products_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
