# Generated by Django 4.2.20 on 2025-06-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_vendorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
