# Generated by Django 4.2.20 on 2025-06-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userId',
        ),
    ]
