# Generated by Django 4.2.20 on 2025-06-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
