# Generated by Django 4.2.20 on 2025-06-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='stock',
        ),
    ]
