# Generated by Django 4.2.20 on 2025-06-16 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_marketplaceproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
