# Generated by Django 4.2.20 on 2025-06-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productsize_stock'),
        ('products', '0006_marketplaceproduct_created_at_and_more'),
    ]

    operations = [
    ]
