# Generated by Django 4.2.20 on 2025-06-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_marketplaceproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
