# Generated by Django 4.2.20 on 2025-06-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_marketplaceproduct_isapproved'),
        ('products', '0007_merge_20250623_1422'),
    ]

    operations = [
    ]
