# Generated by Django 4.2.20 on 2025-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20250623_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initialStock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isFeatured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.AddField(
            model_name='product',
            name='discountPercentage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
