# Generated by Django 4.2.20 on 2025-08-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_initialstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('FX', 'Fixed Size')], max_length=2),
        ),
    ]
