# Generated by Django 4.2.20 on 2025-08-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productsize_stock'),
        ('products', '0010_productsize_stock_alter_productsize_size'),
    ]

    operations = [
    ]
