# Generated by Django 4.2.20 on 2025-08-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_merge_20250819_0852'),
        ('products', '0012_add_has_sizes_field'),
    ]

    operations = [
    ]
